// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package repository

var TableNames = struct {
	SchemaMigrations string
	TBlog            string
	TUser            string
}{
	SchemaMigrations: "schema_migrations",
	TBlog:            "t_blog",
	TUser:            "t_user",
}
