// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package repository

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testTUsers(t *testing.T) {
	t.Parallel()

	query := TUsers()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testTUsersDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TUser{}
	if err = randomize.Struct(seed, o, tUserDBTypes, true, tUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := TUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTUsersQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TUser{}
	if err = randomize.Struct(seed, o, tUserDBTypes, true, tUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := TUsers().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := TUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTUsersSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TUser{}
	if err = randomize.Struct(seed, o, tUserDBTypes, true, tUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := TUserSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := TUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTUsersExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TUser{}
	if err = randomize.Struct(seed, o, tUserDBTypes, true, tUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := TUserExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if TUser exists: %s", err)
	}
	if !e {
		t.Errorf("Expected TUserExists to return true, but got false.")
	}
}

func testTUsersFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TUser{}
	if err = randomize.Struct(seed, o, tUserDBTypes, true, tUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	tUserFound, err := FindTUser(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if tUserFound == nil {
		t.Error("want a record, got nil")
	}
}

func testTUsersBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TUser{}
	if err = randomize.Struct(seed, o, tUserDBTypes, true, tUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = TUsers().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testTUsersOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TUser{}
	if err = randomize.Struct(seed, o, tUserDBTypes, true, tUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := TUsers().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testTUsersAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	tUserOne := &TUser{}
	tUserTwo := &TUser{}
	if err = randomize.Struct(seed, tUserOne, tUserDBTypes, false, tUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TUser struct: %s", err)
	}
	if err = randomize.Struct(seed, tUserTwo, tUserDBTypes, false, tUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = tUserOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = tUserTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := TUsers().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testTUsersCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	tUserOne := &TUser{}
	tUserTwo := &TUser{}
	if err = randomize.Struct(seed, tUserOne, tUserDBTypes, false, tUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TUser struct: %s", err)
	}
	if err = randomize.Struct(seed, tUserTwo, tUserDBTypes, false, tUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = tUserOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = tUserTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func tUserBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *TUser) error {
	*o = TUser{}
	return nil
}

func tUserAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *TUser) error {
	*o = TUser{}
	return nil
}

func tUserAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *TUser) error {
	*o = TUser{}
	return nil
}

func tUserBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *TUser) error {
	*o = TUser{}
	return nil
}

func tUserAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *TUser) error {
	*o = TUser{}
	return nil
}

func tUserBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *TUser) error {
	*o = TUser{}
	return nil
}

func tUserAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *TUser) error {
	*o = TUser{}
	return nil
}

func tUserBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *TUser) error {
	*o = TUser{}
	return nil
}

func tUserAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *TUser) error {
	*o = TUser{}
	return nil
}

func testTUsersHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &TUser{}
	o := &TUser{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, tUserDBTypes, false); err != nil {
		t.Errorf("Unable to randomize TUser object: %s", err)
	}

	AddTUserHook(boil.BeforeInsertHook, tUserBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	tUserBeforeInsertHooks = []TUserHook{}

	AddTUserHook(boil.AfterInsertHook, tUserAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	tUserAfterInsertHooks = []TUserHook{}

	AddTUserHook(boil.AfterSelectHook, tUserAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	tUserAfterSelectHooks = []TUserHook{}

	AddTUserHook(boil.BeforeUpdateHook, tUserBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	tUserBeforeUpdateHooks = []TUserHook{}

	AddTUserHook(boil.AfterUpdateHook, tUserAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	tUserAfterUpdateHooks = []TUserHook{}

	AddTUserHook(boil.BeforeDeleteHook, tUserBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	tUserBeforeDeleteHooks = []TUserHook{}

	AddTUserHook(boil.AfterDeleteHook, tUserAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	tUserAfterDeleteHooks = []TUserHook{}

	AddTUserHook(boil.BeforeUpsertHook, tUserBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	tUserBeforeUpsertHooks = []TUserHook{}

	AddTUserHook(boil.AfterUpsertHook, tUserAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	tUserAfterUpsertHooks = []TUserHook{}
}

func testTUsersInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TUser{}
	if err = randomize.Struct(seed, o, tUserDBTypes, true, tUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testTUsersInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TUser{}
	if err = randomize.Struct(seed, o, tUserDBTypes, true); err != nil {
		t.Errorf("Unable to randomize TUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(tUserColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := TUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testTUserToManyAuthorTBlogs(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a TUser
	var b, c TBlog

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, tUserDBTypes, true, tUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TUser struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, tBlogDBTypes, false, tBlogColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, tBlogDBTypes, false, tBlogColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.Author = a.Email
	c.Author = a.Email

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.AuthorTBlogs().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.Author == b.Author {
			bFound = true
		}
		if v.Author == c.Author {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := TUserSlice{&a}
	if err = a.L.LoadAuthorTBlogs(ctx, tx, false, (*[]*TUser)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.AuthorTBlogs); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.AuthorTBlogs = nil
	if err = a.L.LoadAuthorTBlogs(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.AuthorTBlogs); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testTUserToManyAddOpAuthorTBlogs(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a TUser
	var b, c, d, e TBlog

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, tUserDBTypes, false, strmangle.SetComplement(tUserPrimaryKeyColumns, tUserColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*TBlog{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, tBlogDBTypes, false, strmangle.SetComplement(tBlogPrimaryKeyColumns, tBlogColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*TBlog{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddAuthorTBlogs(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.Email != first.Author {
			t.Error("foreign key was wrong value", a.Email, first.Author)
		}
		if a.Email != second.Author {
			t.Error("foreign key was wrong value", a.Email, second.Author)
		}

		if first.R.AuthorTUser != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.AuthorTUser != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.AuthorTBlogs[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.AuthorTBlogs[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.AuthorTBlogs().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testTUsersReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TUser{}
	if err = randomize.Struct(seed, o, tUserDBTypes, true, tUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testTUsersReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TUser{}
	if err = randomize.Struct(seed, o, tUserDBTypes, true, tUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := TUserSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testTUsersSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TUser{}
	if err = randomize.Struct(seed, o, tUserDBTypes, true, tUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := TUsers().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	tUserDBTypes = map[string]string{`ID`: `uuid`, `Username`: `character varying`, `Email`: `USER-DEFINED`, `Salt`: `character varying`, `Password`: `character varying`, `CreateTime`: `timestamp without time zone`, `UpdateTime`: `timestamp without time zone`}
	_            = bytes.MinRead
)

func testTUsersUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(tUserPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(tUserAllColumns) == len(tUserPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &TUser{}
	if err = randomize.Struct(seed, o, tUserDBTypes, true, tUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, tUserDBTypes, true, tUserPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TUser struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testTUsersSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(tUserAllColumns) == len(tUserPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &TUser{}
	if err = randomize.Struct(seed, o, tUserDBTypes, true, tUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, tUserDBTypes, true, tUserPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TUser struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(tUserAllColumns, tUserPrimaryKeyColumns) {
		fields = tUserAllColumns
	} else {
		fields = strmangle.SetComplement(
			tUserAllColumns,
			tUserPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := TUserSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testTUsersUpsert(t *testing.T) {
	t.Parallel()

	if len(tUserAllColumns) == len(tUserPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := TUser{}
	if err = randomize.Struct(seed, &o, tUserDBTypes, true); err != nil {
		t.Errorf("Unable to randomize TUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert TUser: %s", err)
	}

	count, err := TUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, tUserDBTypes, false, tUserPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TUser struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert TUser: %s", err)
	}

	count, err = TUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
