grpc:
  host: "localhost"
  network: "tpc"
  port: 64532

log:
  service-name: "search-service"
  level: 1
  time-format: "2006-01-02T15:04:05Z07:00"
  timestamp-enabled: true

db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "docker"
  db-name: "postgres"
  ssl-mode: "disable"

redis:
  host: "localhost"
  port: 6379
  password: "pwd"
  db: 0
  max-retries: 3
chunk-size: 1000
